### PR TITLE
use crate2nix

### PR DESCRIPTION
**Pull request by LnL7**
We've run into various issues with carnix, some have been patched already but I'm not sure how to fix other issues like #498. Crate2nix seems to handle all of the cases we have ran into so far.

### CODE REVIEW

**Comment by andir** [comment]
Maybe use `cargo update` or `cargo lock` instead of the `cargo build`
invocation in nix/update-crates.sh as otherwise you impurely require all
the build inputs in the shell.

**Comment by LnL7** [comment]
Yeah, but this is how it was before. Doesn't it make sense to ensure everything actually builds before updating?

**Comment by andir** [comment]
I would argue it is time to fix that nix-shell shebang to contain the build
dependencies.

**Review by cole-h — CHANGES_REQUESTED** [review]
Probably want to remove Carnix from `nix/overlay.nix` and `shell.nix`, as well:

https://github.com/NixOS/ofborg/blob/65db4d0da04f725ccbb2d92efa3fb69f0c5a8625/nix/overlay.nix#L3

https://github.com/NixOS/ofborg/blob/65db4d0da04f725ccbb2d92efa3fb69f0c5a8625/shell.nix#L86

**Review by cole-h — APPROVED** [review]
> +5,293 −7,724 

Nice! LGTM. Hopefully this requires less patching than Carnix did ;)

**Pull request merged**
