### PR TITLE
add label for exactly 1 rebuild

### PR DESCRIPTION
**Pull request by ryantm**
It is fundamentally different to review a leaf package with no other reverse dependencies in Nixpkgs and one that has at least one reverse dependency, so make those separate labels.

I expect rolling this out is going to have to coincide with updating the labels and adding the new labels.

### CODE REVIEW

**Comment by grahamc** [comment]
This is a good idea. I'd like to continue applying the `1-10` label in the `1` case, so existing searches continue to work.

**Comment by ryantm** [comment]
@grahamc Okay, done, and I added the proper tests now. Also, your suggestion makes this change will be backward compatible, so that's nice!

By the way, I didn't commit this but in order to build this I had to add the `dyn` annotation in 7 places because of this error:

`error: trait objects without an explicit `dyn` are deprecated`

If you want me to add those `dyn` annotations to this branch, I can.

**Comment by grahamc** [comment]
Please do add the annotations :)

**Comment by ryantm** [comment]
@grahamc Added.

**Comment by ryantm** [comment]
@grahamc Do you need anything else from me to merge this?

**Comment by ryantm** [comment]
Even though the CI is failing, I think this is ready to go, because the CI errors seem unrelated.

**Pull request merged**
