### PR TITLE
add ryantm to config.public.json

### PR DESCRIPTION
**Pull request by ryantm**
Hi.

@Mic92 [asked me](https://github.com/NixOS/nixpkgs/pull/35563#issuecomment-368340514) to apply for access. Can I have access?

Ryan

### CODE REVIEW

**Comment by grahamc** [comment]
ok deployed, thanks!

**Comment by LnL7** [comment]
Isn't known_uses more appropriate for most contributors?

**Comment by grahamc** [comment]
Most, yeah, @ryantm has just been around a long time and thought this was ok: https://github.com/NixOS/nixpkgs/search?o=asc&q=author%3Aryantm&s=created&type=Issues&utf8=%E2%9C%93

**Comment by LnL7** [comment]
Oh! Never mind then 😄

**Pull request merged**
