### PR TITLE
nixpkgs-rs: build .passthru.tests too

### LINKED ISSUE #368: Build passthru.tests automatically along with the package
I often have to manually call a `build nixosTests.<foo>` when checking a PR. I'm slowly adding them to `passthru.tests`, and since https://github.com/ryantm/nixpkgs-update/pull/118 r-ryantm is taking them into account, but it'd be great if ofborg also automatically checked the derivations listed in `passthru.tests`

Building `<package>.tests or {}` in addition to `<package>` should (hopefully) be enough, and not be too hard to implement. This would let the maintainers responsible for determining which tests must pass to consider a change to a package valid.

What do you think about this?

### PR DESCRIPTION
**Pull request by Ekleog**
Fixes https://github.com/NixOS/ofborg/issues/368

### CODE REVIEW

**Comment by Ekleog** [comment]
Note: only the first commit is actually meaningful, the other ones are fixes to the existing codebase so that travis passes after the latest rust/clippy/fmt updates.

**Comment by Ekleog** [comment]
cc @Profpatsch

**Comment by Ekleog** [comment]
@grahamc Poke

**Comment by Ekleog** [comment]
@grahamc Poke (it's a 3-line PR ;))

**Comment by worldofpeace** [comment]
@grahamc also poke :rofl: (it's a summoning ritual)

**Comment by Profpatsch** [comment]
It’s the magic poke!

**Pull request merged**
