### PR TITLE
d-goldin: Adding myself

### PR DESCRIPTION
**Pull request by d-goldin**
I'd like to be able to test some PRs a bit better myself without
relying on another contributor for everything.

### CODE REVIEW

**Comment by d-goldin** [comment]
Ideally I'd also like to be able to build on darwin, especially because I have zero access to any darwin resources myself, but I'm not sure what's required for that level of trust.

**Comment by d-goldin** [comment]
@fpletz: As discussed. Thanks in advance.

**Comment by fpletz** [comment]
I am happy to vouch for @d-goldin since his technical expertise is great, he has already contributed to nixpkgs in the past and he wants to contribute even more.

**Comment by d-goldin** [comment]
Thanks!

**Pull request merged**
