### PR TITLE
add symphorien to known users

### PR DESCRIPTION
**Pull request by symphorien**

### CODE REVIEW

**Comment by Ekleog** [comment]
:+1:

**Comment by veprbl** [comment]
I was just about to submit the same request.

**Comment by grahamc** [comment]
Thanks for the PR,  but no need: all users are considered "known users" now, and being in the "known user" list doesn't grant anyone any special access.

**Comment by veprbl** [comment]
@grahamc So everyone can build on darwin or not? I think I saw a PR without a darwin build that day.

**Comment by veprbl** [comment]
I guess should target trusted_users in config.public.json instead

**Comment by cole-h** [comment]
Yes, being added to `trusted_users` in config.public.json is necessary for Darwin builds, while (I believe) everybody can ask ofborg to build `aarch64-linux` and `x86_64-linux`.

**Pull request closed without merging**
