### PR TITLE
update cargo deps

### PR DESCRIPTION
**Pull request by Artturin**
this includes the commits from https://github.com/NixOS/ofborg/pull/618

plus some semver MAJOR updates

### CODE REVIEW

**Comment by cole-h** [comment]
Appreciate this, thanks!

Since this has a greater chance of breaking things, I'm going to hold off on merging this until tomorrow (and make sure the stuff I merged earlier didn't have any adverse effects).

**Comment by Artturin** [comment]
@cole-h reminder

**Comment by cole-h** [comment]
Thanks! Got unexpectedly busy yesterday 😅 I'll get on this soon.

**Comment by cole-h** [comment]
Alright, let's see how this goes!

**Pull request merged**
