### PR TITLE
FUNDING: use the shared .github FUNDING yaml

### PR DESCRIPTION
**Pull request by zimbatm**
The funding is now configured in NixOS/.github/FUNDING.yml

### CODE REVIEW

**Review by worldofpeace — APPROVED** [review]

**Comment by worldofpeace** [comment]
@grahamc ^

**Comment by worldofpeace** [comment]
Actually, is the patreon still an option?
If so this would remove its visibility.

**Review by worldofpeace — CHANGES_REQUESTED** [review]
See above comment

**Comment by zimbatm** [comment]
@worldofpeace yes we are still figuring out what to do with the patreon

**Comment by davidak** [comment]
Why not have information about funding options here too?

It's duplicated information, but maybe people find this repo. That might increase the chance we get more funding.

**Comment by grahamc** [comment]
We'll do this shortly, I'll probably change to submitting expenses to the OpenCollective, and forward all the money from the ofborg patreon to the OpenCollective project.

**Comment by davidak** [comment]
>forward all the money from the ofborg patreon to the OpenCollective project.

please make sure not to pay fees twice

**Pull request closed without merging**
