### PR TITLE
Clippy and cargo fmt

### PR DESCRIPTION
**Pull request by grahamc**
Also code to check these things in Travis.

### CODE REVIEW

**Comment by grahamc** [comment]
I'd be wildly surprised if anyone wanted to review this. `cargo test` passed on every clippy change, and then rustfmt went wild. It is probably fine. Merging on green.

**Comment by domenkozar** [comment]
@grahamc any reason for me to review this?

**Comment by grahamc** [comment]
Sorry, I made a mistake on the UI.

**Comment by domenkozar** [comment]
Sir, you are forgiven.

**Pull request merged**
