### PR TITLE
Clarify autobuild commit parsing

### PR DESCRIPTION
**Pull request by aneeshusa**
I didn't realize the bot would recognize all commits, not just version bumps, since all the examples use version bumps, and inadvertenly retriggered the bot on https://github.com/NixOS/nixpkgs/pull/36283 without realizing it was already autobuilding.

Thanks again for the bot @grahamc, it's invaluable!

### CODE REVIEW

**Comment by aneeshusa** [comment]
Also, I just noticed the bot didn't seem to kick off a fresh autobuild when I force pushed to https://github.com/NixOS/nixpkgs/pull/35891 to bump to 2017.7.4 instead of 2017.7.3 - can you clarify the exact behavior of when it will/won't happen? Ideally it will be fixed soon, but in the meantime I'd like to document it.

**Review by 7c6f434c — APPROVED** [review]

**Comment by 7c6f434c** [comment]
I think the last build is for `2017.7.4` and it was auto-triggered? Maybe there was some lag, though.

**Comment by aneeshusa** [comment]
Looking at the PR again it does seem to have auto-triggered the jobs for 2017.7.4, I must have missed them.

**Comment by grahamc** [comment]
Hey, this looks great. Thank you! I've been shifting some of the ofborg services to new hardware today, causing some delay in processing. Here you can see the backlog: https://monitoring.nix.ci/dashboard/db/ofborg?refresh=10s&orgId=1&from=1520209152159&to=1520212752159&panelId=9&fullscreen I just brought up a second builder, and will be working with other ofborg builder hosts to move to the new infra too.

**Pull request merged**
