### PR TITLE
Nom

### PR DESCRIPTION
**Pull request by Ekleog**
This mostly rewrites the comment parser to use nom.

I've also added the `nixos-test` alias for `test`, and bumped `Cargo.lock` on my way there. If you want me to separate one of these modifications to a separate PR, just tell me!

Also, currently the dependency on `nom` is on its master branch: on my way there I hit a bug in nom, that will have to wait for `4.0.0-beta3` to be released before it's available on crates.io.

### CODE REVIEW

**Comment by grahamc** [comment]
I'd like to merge this, but:

1. please rebase against `next`
2. update the carnix file with `./nix/update-carnix.sh`
3. please drop the nixos-test command for now

**Comment by Ekleog** [comment]
Done, thanks for the `./nix/update-carnix.sh` hint!

I've checked after the rebase, and `nix-build` in `<root>/ofborg` manages to build, and `cargo test` in the same directory fails no additional tests compared to the ones currently failing on `next`.

**Comment by grahamc** [comment]
LGTM I will merge this in the next couple days. I'm going to be traveling starting in 10min so I don't want to deeploy it now :)

**Comment by Ekleog** [comment]
Great, thanks! Have a nice trip :)

**Pull request merged**
