### PR TITLE
Nixpkgs tests

### PR DESCRIPTION
**Pull request by Ekleog**
First draft of adding support for nixpkgs tests as per https://github.com/NixOS/nixpkgs/pull/36842.

Builds upon https://github.com/NixOS/ofborg/pull/124 ; this is a completely untested PR, mostly there to illustrate addition of a new keyword.

### CODE REVIEW

**Comment by Profpatsch** [comment]
Ideally, we can scrap the `test` and `nixpkgs-test` commands in the future, see the bullet points in https://github.com/NixOS/nixpkgs/pull/36842#issuecomment-373876012.

**Comment by 7c6f434c** [comment]
@Profpatsch Well, that is a very long-term ideally. Right now ofBorg doesn't even build all the changed derivations themselves…

**Comment by grahamc** [comment]
Probably not a thing we should do unless nixpkgs supports it properly.

**Comment by Ekleog** [comment]
Indeed, I had completely forgot this PR was still open, should have closed it when https://github.com/NixOS/nixpkgs/pull/36842 stalled, sorry! :)

**Pull request closed without merging**
